# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d21564dd02a972d2b0dd855ac3beb58cffe0db59dd2dae5c5b9e93cec53cb8666998e8b8042bd96620ac0888b6d9e1370917a8cf175567a629df0b5061de19db

test:
  secret_key_base: 97b4d80cd35c4791c73f41ee578e71dfd91fd6c7f3f15dc9c90cb7b7ce37cba05c93b5b58ed9aadcf3ecbb292a2d96b6aa3a89a2ce561242cf04c8e96e35a446

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
